### ISSUE TITLE
Service provider not loaded when running queue:listen

### ISSUE THREAD

**Issue by Lambik** [cooperaj/laravel-redis-sentinel#3]
Hi,

I've had a problem with your code, namely the service provider does not boot/register when I run `php artisan queue:listen sentinel`. Instead, I get the error "queue driver sentinel-redis not found" (because of course the boot method has not been called).

The only solution I have found was to set $defer to false. Do you have an idea what the cause could be?

Best regards,
  Tom

**Comment by andrewmclagan** [comment]
also see this `^0.3.0`

**Comment by cooperaj** [comment]
I notice you've got a fork with this presumably fixed? If you want I can PR it in?

**Comment by cooperaj** [comment]
Fixed in dev-master
