### ISSUE TITLE
Call to undefined method RedisSentinel\Laravel\SentinelQueue::setExpire()

### ISSUE THREAD

**Issue by ronnievisser** [cooperaj/laravel-redis-sentinel#4]
Hi,

I got this error on laravel 5.4. it's called from /src/RedisSentinel/Laravel/SentinelConnector.php:22

can this be fixed?

thanks

**Comment by cooperaj** [comment]
I notice you've got a fork with this presumably fixed? If you want I can PR it in?

Was the setExpire method removed in 5.4 then?

**Comment by ronnievisser** [comment]
Hi,

The setExpire method is indeed removed.

Regards

**Comment by cooperaj** [comment]
Is now fixed.
